version: "3"

services:
    minecraft-fe:
        build: .
        image: kainosekai/minecraft-fe:latest
        container_name: minecraft-fe
        ports:
            - ${PORT}:443
        tty: true
        restart: unless-stopped
        volumes:
            - ${DOCKER_SSL_CERTS_PATH}:/etc/ssl/certs
            - ${DOCKER_SSL_CONFS_PATH}:/etc/ssl/confs
