version: "3"

services:
    minecraft-fe:
        build: .
        image: kainosekai/minecraft-fe
        container_name: minecraft-fe
        ports:
            - 8080:80
        tty: true
        restart: unless-stopped
