version: "3"

services:
    minecraft-fe:
        build: .
        image: kainosekai/minecraft-fe:latest
        container_name: minecraft-fe
        ports:
            - 20443:443
        tty: true
        restart: unless-stopped
        volumes:
            - ${DOCKER_CERTS_PATH}:/etc/ssl/certs
