version: "3.5"

services:
  minecraft-fe:
    build: .
    image: kylerfrazier/minecraft-frontend:latest
    container_name: minecraft-frontend
    networks:
      - kainosekai
    ports:
      - 443:443
    tty: true
    restart: unless-stopped
    volumes:
      - ${DOCKER_SSL_PATH}:/etc/ssl

networks:
  kainosekai:
    name: kainosekai
    external: true
