version: "3"

services:
    minecraft-fe:
        build: .
        image: kainosekai/minecraft-fe:latest
        container_name: minecraft-fe
        ports:
            - 20080:80
        extra_hosts:
            - host.docker.internal:host-gateway
        tty: true
        restart: unless-stopped
        volumes:
            - /etc/nginx/certs:/etc/nginx/certs
