version: "3"

services:
    minecraft-fe:
        build: .
        image: kainosekai/minecraft-fe:latest
        container_name: minecraft-fe
        ports:
            - 20080:80
        tty: true
        restart: unless-stopped
