version: "3.5"

services:
  minecraft-fe:
    build: .
    image: kainosekai/minecraft-fe:latest
    container_name: minecraft-fe
    ports:
      - ${PORT}:443
    tty: true
    restart: unless-stopped
    volumes:
      - ${DOCKER_SSL_PATH}:/etc/ssl

networks:
  infrared:
    name: kainosekai
