name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env: 
  DOCKER_USER: ${{ secrets.DOCKER_USER }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure Docker Compose
      env:
        DOCKER_COMPOSE_ENV: ${{ secrets.DOCKER_COMPOSE_ENV }}
      run: echo $DOCKER_COMPOSE_ENV > .env
    - name: Build the Docker image
      run: docker-compose build
    - name: Dockerhub login
      env: 
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
    - name: Push the Docker image
      run: docker push $DOCKER_USER/minecraft-frontend:latest
